### ISSUE TITLE
监听事件埋点bug

### ISSUE THREAD

**Issue by sheepYC** [imTik/npm-buriedDot#1]
直接在UI组件或某父元素上设置data-dot，点击其内部元素，e.target获取的是子元素，无法获取data-dot属性。

**Comment by imTik** [comment]
是的，因为我比较懒， 没做向上循环判断，哈哈，我明天给加上吧。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sheepYC"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 下午5:54
收件人:&nbsp;"imTik/npm-buriedDot"<npm-buriedDot@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[imTik/npm-buriedDot] 监听事件埋点bug (#1)





 
直接在UI组件或某父元素上设置data-dot，点击其内部元素，e.target获取的是子元素，无法获取data-dot属性。

**Comment by sheepYC** [comment]
哈哈你回复超快的，早上要拉代码的时候发现20分钟前更新，热腾腾的。

**Comment by imTik** [comment]
Hello, [监听事件埋点bug&nbsp;] 已修复， 最新版本号1.0.5，&nbsp; 感谢你的使用哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sheepYC"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 晚上6:04
收件人:&nbsp;"imTik/npm-buriedDot"<npm-buriedDot@noreply.github.com&gt;;
抄送:&nbsp;"关加豪。"<275151754@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [imTik/npm-buriedDot] 监听事件埋点bug (#1)





 
哈哈你回复超快的，早上要拉代码的时候发现20分钟前更新，热腾腾的。
